from django.urls import path

from .views import (
    ExamBlueprintCloneView,
    ExamBlueprintDetailView,
    ExamBlueprintListCreateView,
    ExamBlueprintTransitionView,
    ExamSetCloneView,
    ExamSetDetailView,
    ExamSetListCreateView,
    ExamSetTransitionView,
    QuestionDetailView,
    QuestionListCreateView,
    QuestionTransitionView,
    QuestionTypeAdminDetailView,
    QuestionTypeAdminListCreateView,
    SubjectAdminDetailView,
    SubjectAdminListCreateView,
    TopicAdminDetailView,
    TopicAdminListCreateView,
)

urlpatterns = [
    path("blueprints/", ExamBlueprintListCreateView.as_view(), name="blueprint_list"),
    path("blueprints/<int:blueprint_id>/", ExamBlueprintDetailView.as_view(), name="blueprint_detail"),
    path("blueprints/<int:blueprint_id>/clone/", ExamBlueprintCloneView.as_view(), name="blueprint_clone"),
    path("blueprints/<int:blueprint_id>/transition/", ExamBlueprintTransitionView.as_view(), name="blueprint_transition"),
    path("exam-sets/", ExamSetListCreateView.as_view(), name="exam_set_list"),
    path("exam-sets/<int:exam_set_id>/", ExamSetDetailView.as_view(), name="exam_set_detail"),
    path("exam-sets/<int:exam_set_id>/clone/", ExamSetCloneView.as_view(), name="exam_set_clone"),
    path("exam-sets/<int:exam_set_id>/transition/", ExamSetTransitionView.as_view(), name="exam_set_transition"),
    path("questions/", QuestionListCreateView.as_view(), name="question_list"),
    path("questions/<int:question_id>/", QuestionDetailView.as_view(), name="question_detail"),
    path("questions/<int:question_id>/transition/", QuestionTransitionView.as_view(), name="question_transition"),
    path("admin/subjects/", SubjectAdminListCreateView.as_view(), name="subject_list"),
    path("admin/subjects/<int:subject_id>/", SubjectAdminDetailView.as_view(), name="subject_detail"),
    path("admin/question-types/", QuestionTypeAdminListCreateView.as_view(), name="question_type_list"),
    path("admin/question-types/<int:question_type_id>/", QuestionTypeAdminDetailView.as_view(), name="question_type_detail"),
    path("admin/topics/", TopicAdminListCreateView.as_view(), name="topic_list"),
    path("admin/topics/<int:topic_id>/", TopicAdminDetailView.as_view(), name="topic_detail"),
]
