# Generated by Django 5.2.3 on 2026-08-05 10:56

import apps.attendance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('test_center', models.CharField(blank=True, max_length=255)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('seat', models.CharField(blank=True, max_length=50)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Permit can no longer be used to check in after this time; null means no expiry set.', null=True)),
                ('qr_token', models.CharField(default=apps.attendance.models.generate_qr_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('USED', 'Used'), ('VOID', 'Void')], default='ISSUED', max_length=16)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_scans', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.exampermit')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
