# Generated by Django 5.2.3 on 2026-08-06 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_examslot_studentapplication_exam_status_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampermit',
            name='application',
            field=models.OneToOneField(blank=True, help_text='The web-side application this permit was auto-issued for, if any. Null for permits created another way (e.g. the seed_sample_permits command).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_permit', to='applications.studentapplication'),
        ),
    ]
