# Generated by Django 5.2.3 on 2026-08-06 12:06

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_bulk_upload_application_metadata'),
        ('attendance', '0001_initial'),
        ('results', '0007_scorereleasenotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_center', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=160)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['test_center', 'code'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('test_center'), django.db.models.functions.text.Lower('code'), name='attendance_unique_room_code_per_center')],
            },
        ),
        migrations.CreateModel(
            name='RoomSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('late_after_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_sessions', to='results.examinationsession')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='attendance.examroom')),
            ],
            options={
                'ordering': ['starts_at', 'room__test_center', 'room__code'],
            },
        ),
        migrations.CreateModel(
            name='CandidateSessionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_session_assignments', to='applications.studentapplication')),
                ('room_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_assignments', to='attendance.roomsession')),
            ],
            options={
                'ordering': ['room_session__starts_at', 'seat_label'],
            },
        ),
        migrations.CreateModel(
            name='RoomSessionProctorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('proctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_room_assignments', to=settings.AUTH_USER_MODEL)),
                ('room_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proctor_assignments', to='attendance.roomsession')),
            ],
            options={
                'ordering': ['room_session__starts_at', 'assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceState',
            fields=[
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='attendance_state', serialize=False, to='attendance.candidatesessionassignment')),
                ('status', models.CharField(choices=[('UNMARKED', 'Unmarked'), ('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], default='UNMARKED', max_length=16)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('QR_SCAN', 'QR scan'), ('SYNC', 'Sync')], default='', max_length=16)),
                ('last_client_instance_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_client_event_id', models.UUIDField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_attendance_states', to=settings.AUTH_USER_MODEL)),
                ('room_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_states', to='attendance.roomsession')),
            ],
            options={
                'ordering': ['room_session__starts_at', 'assignment__seat_label'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_status', models.CharField(choices=[('UNMARKED', 'Unmarked'), ('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], max_length=16)),
                ('previous_status', models.CharField(blank=True, choices=[('UNMARKED', 'Unmarked'), ('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], default='', max_length=16)),
                ('resulting_status', models.CharField(blank=True, choices=[('UNMARKED', 'Unmarked'), ('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], default='', max_length=16)),
                ('event_type', models.CharField(choices=[('MANUAL', 'Manual'), ('QR_SCAN', 'QR scan'), ('SYNC', 'Sync'), ('CORRECTION', 'Correction')], max_length=16)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('QR_SCAN', 'QR scan'), ('SYNC', 'Sync')], max_length=16)),
                ('outcome', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('CONFLICT', 'Conflict'), ('SESSION_CLOSED', 'Session closed')], max_length=20)),
                ('client_instance_id', models.CharField(blank=True, default='', max_length=128)),
                ('client_event_id', models.UUIDField(blank=True, null=True)),
                ('sync_batch_id', models.UUIDField(blank=True, null=True)),
                ('client_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('server_received_at', models.DateTimeField(auto_now_add=True)),
                ('correction_reason', models.CharField(blank=True, default='', max_length=240)),
                ('resulting_version', models.PositiveBigIntegerField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='attendance.candidatesessionassignment')),
            ],
            options={
                'ordering': ['-server_received_at'],
                'indexes': [models.Index(fields=['assignment', 'server_received_at'], name='attendance_event_history_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_event_id__isnull', False), ('client_instance_id__gt', '')), fields=('client_instance_id', 'client_event_id'), name='attendance_unique_client_event'), models.CheckConstraint(condition=models.Q(('resulting_version__gte', 0)), name='attendance_event_version_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='PermitCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permit_credentials', to='attendance.candidatesessionassignment')),
            ],
            options={
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('assignment',), name='attendance_unique_active_permit'), models.CheckConstraint(condition=models.Q(('is_active', False), ('revoked_at__isnull', True), _connector='OR'), name='attendance_permit_active_not_revoked')],
            },
        ),
        migrations.AddConstraint(
            model_name='roomsession',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='attendance_room_session_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='roomsession',
            constraint=models.CheckConstraint(condition=models.Q(('late_after_at__gte', models.F('starts_at'))), name='attendance_room_session_late_after_start'),
        ),
        migrations.AddConstraint(
            model_name='roomsession',
            constraint=models.CheckConstraint(condition=models.Q(('late_after_at__lte', models.F('ends_at'))), name='attendance_room_session_late_before_end'),
        ),
        migrations.AddIndex(
            model_name='candidatesessionassignment',
            index=models.Index(fields=['room_session', 'seat_label'], name='attendance_roster_seat_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidatesessionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('candidate', 'room_session'), name='attendance_unique_active_candidate_session'),
        ),
        migrations.AddConstraint(
            model_name='candidatesessionassignment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('seat_label'), models.F('room_session'), condition=models.Q(('is_active', True)), name='attendance_unique_active_room_seat_ci'),
        ),
        migrations.AddConstraint(
            model_name='candidatesessionassignment',
            constraint=models.CheckConstraint(condition=models.Q(('seat_label__regex', '.*\\S.*')), name='attendance_seat_label_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='candidatesessionassignment',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), ('revoked_at__isnull', True), _connector='OR'), name='attendance_assignment_active_not_revoked'),
        ),
        migrations.AddConstraint(
            model_name='roomsessionproctorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('room_session', 'proctor'), name='attendance_unique_active_room_proctor'),
        ),
        migrations.AddIndex(
            model_name='attendancestate',
            index=models.Index(fields=['room_session', 'status'], name='attendance_current_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancestate',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 0)), name='attendance_state_version_nonnegative'),
        ),
    ]
