# Generated by Django 5.2.3 on 2026-08-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_exampermit_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampermit',
            name='exam_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exampermit',
            name='exam_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
