# Generated by Django 5.2.3 on 2026-08-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_session_attendance_schema'),
        ('attendance', '0003_exampermit_exam_end_time_exampermit_exam_start_time'),
    ]

    operations = [
    ]
