# Generated by Django 5.2.3 on 2026-08-05 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200)),
                ('program_code', models.CharField(max_length=40)),
                ('program_name', models.CharField(max_length=200)),
                ('degree_type', models.CharField(choices=[('Bachelor of Science', 'Bachelor of Science'), ('Bachelor of Arts', 'Bachelor of Arts'), ('Bachelor of Fine Arts', 'Bachelor of Fine Arts'), ('Associate', 'Associate')], default='Bachelor of Science', max_length=40)),
                ('major_specialization', models.CharField(blank=True, default='', max_length=200)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('cutoff_percentile', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='universities.university')),
            ],
            options={
                'ordering': ['program_code'],
            },
        ),
    ]
