# Generated by Django 5.2.3 on 2026-08-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_collegecourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegecourse',
            name='degree_type',
            field=models.CharField(blank=True, default='Bachelor of Science', max_length=100),
        ),
    ]
