# Generated by Django 5.2.3 on 2026-08-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_alter_collegecourse_degree_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegecourse',
            name='degree_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
