# Generated by Django 5.2.3 on 2026-08-06 07:59

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_alter_collegecourse_degree_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collegecourse',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('program_code'), models.F('university'), name='unique_course_code_per_university'),
        ),
        migrations.AddConstraint(
            model_name='university',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('region'), name='unique_university_name_per_region'),
        ),
    ]
