# Generated by Django 5.2.3 on 2026-08-06 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_collegecourse_unique_course_code_per_university_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['classification', 'status'], name='universitie_classif_7337b6_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['region'], name='universitie_region_896c75_idx'),
        ),
    ]
