# Generated by Django 5.2.3 on 2026-08-04 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('classification', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('examinee_capacity', models.PositiveIntegerField(default=0)),
                ('region', models.CharField(choices=[('NCR', 'National Capital Region (NCR)'), ('CAR', 'Cordillera Administrative Region (CAR)'), ('Region I', 'Ilocos Region (Region I)'), ('Region II', 'Cagayan Valley (Region II)'), ('Region III', 'Central Luzon (Region III)'), ('Region IV-A', 'CALABARZON (Region IV-A)'), ('MIMAROPA', 'MIMAROPA (Region IV-B)'), ('Region V', 'Bicol Region (Region V)'), ('Region VI', 'Western Visayas (Region VI)'), ('Region VII', 'Central Visayas (Region VII)'), ('Region VIII', 'Eastern Visayas (Region VIII)'), ('Region IX', 'Zamboanga Peninsula (Region IX)'), ('Region X', 'Northern Mindanao (Region X)'), ('Region XI', 'Davao Region (Region XI)'), ('Region XII', 'SOCCSKSARGEN (Region XII)'), ('Region XIII', 'Caraga (Region XIII)'), ('BARMM', 'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
