# Generated by Django 5.2.3 on 2026-08-06 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['classification', 'status'], name='schools_sch_classif_5f5f21_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['region'], name='schools_sch_region_367bad_idx'),
        ),
    ]
