# Generated by Django 5.2.3 on 2026-08-05 09:06

import apps.exam_reviews.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0013_studentapplicationadditionalattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamReviewRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_code', models.CharField(max_length=40, unique=True)),
                ('exam_set_code', models.CharField(max_length=40)),
                ('submitted_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('FINALIZED', 'Finalized')], db_index=True, default='SUBMITTED', max_length=20)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('system_initial_score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField()),
                ('pending_subjective_items', models.PositiveIntegerField(default=0)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=80)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_review_records', to='applications.studentapplication')),
            ],
            options={
                'ordering': ['-submitted_at', 'attempt_code'],
            },
        ),
        migrations.CreateModel(
            name='ExamReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('subject', models.CharField(choices=[('MATH', 'Math'), ('ENGLISH', 'English'), ('FILIPINO', 'Filipino'), ('SCIENCE', 'Science')], max_length=12)),
                ('item_number', models.PositiveSmallIntegerField()),
                ('item_type', models.CharField(choices=[('OBJECTIVE', 'Objective'), ('SUBJECTIVE', 'Subjective')], max_length=12)),
                ('question_text', models.TextField()),
                ('answer_options', models.JSONField(blank=True, default=list)),
                ('student_answer', models.TextField()),
                ('expected_answer', models.TextField()),
                ('response_seconds', models.PositiveIntegerField(default=0)),
                ('rubric_text', models.TextField(blank=True, default='')),
                ('ai_proposed_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('response_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('points_awarded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_points', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='exam_reviews.examreviewrecord')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ExamReviewAnswerSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=160, upload_to=apps.exam_reviews.models.answer_sheet_upload_to)),
                ('content_type', models.CharField(max_length=32)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('template_source', models.CharField(choices=[('STANDARD_CSV', 'Standard CSV'), ('HANDWRITTEN_OCR', 'Handwritten OCR'), ('OMR_TEMPLATE_PAPER', 'OMR Template Paper')], default='STANDARD_CSV', max_length=24)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to='exam_reviews.examreviewrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='examreviewrecord',
            constraint=models.CheckConstraint(condition=models.Q(('total_score__lte', models.F('max_score'))), name='exam_review_total_score_lte_max'),
        ),
        migrations.AddConstraint(
            model_name='examreviewrecord',
            constraint=models.CheckConstraint(condition=models.Q(('system_initial_score__lte', models.F('max_score'))), name='exam_review_initial_score_lte_max'),
        ),
        migrations.AddConstraint(
            model_name='examreviewitem',
            constraint=models.UniqueConstraint(fields=('review', 'position'), name='exam_review_item_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='examreviewitem',
            constraint=models.UniqueConstraint(fields=('review', 'subject', 'item_number'), name='exam_review_item_unique_subject_number'),
        ),
        migrations.AddConstraint(
            model_name='examreviewitem',
            constraint=models.CheckConstraint(condition=models.Q(('points_awarded__isnull', True), ('points_awarded__lte', models.F('max_points')), _connector='OR'), name='exam_review_item_score_lte_max'),
        ),
        migrations.AddConstraint(
            model_name='examreviewitem',
            constraint=models.CheckConstraint(condition=models.Q(('ai_proposed_score__isnull', True), ('ai_proposed_score__lte', models.F('max_points')), _connector='OR'), name='exam_review_item_ai_score_lte_max'),
        ),
    ]
