# Generated by Django 5.2.3 on 2026-07-30 17:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_remove_accountprofile_api_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlueprintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlueprintVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.DecimalField(decimal_places=2, max_digits=6)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('academic_review', 'Academic review'), ('revision_required', 'Revision required'), ('approved', 'Approved'), ('published', 'Published'), ('retired', 'Retired'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_choices', models.BooleanField(default=True)),
                ('active_items_only', models.BooleanField(default=True)),
                ('shared_stimulus_required', models.BooleanField(default=False)),
                ('shared_stimulus_min_count', models.PositiveIntegerField(default=0)),
                ('shared_stimulus_questions_per_stimulus', models.PositiveIntegerField(default=0)),
                ('max_item_reuse_count', models.PositiveIntegerField(default=0)),
                ('version_compatibility', models.CharField(default='>= 1.0', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blueprint_versions', to='exams.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_blueprint_versions', to='accounts.accountprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_blueprint_versions', to='accounts.accountprofile')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_blueprint_versions', to='accounts.accountprofile')),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retired_blueprint_versions', to='accounts.accountprofile')),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlueprintSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.PositiveIntegerField()),
                ('section_name', models.CharField(max_length=255)),
                ('item_count', models.PositiveIntegerField()),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=8)),
                ('passing_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_limit_minutes', models.PositiveIntegerField()),
                ('instructions', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField()),
                ('cognitive_levels', models.JSONField(blank=True, default=dict)),
                ('competencies', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.blueprintversion')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blueprint_sections', to='exams.subject')),
            ],
            options={
                'ordering': ['display_order', 'section_number'],
            },
        ),
        migrations.CreateModel(
            name='BlueprintWorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('academic_review', 'Academic review'), ('revision_required', 'Revision required'), ('approved', 'Approved'), ('published', 'Published'), ('retired', 'Retired'), ('archived', 'Archived')], max_length=32, null=True)),
                ('new_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('academic_review', 'Academic review'), ('revision_required', 'Revision required'), ('approved', 'Approved'), ('published', 'Published'), ('retired', 'Retired'), ('archived', 'Archived')], max_length=32)),
                ('action', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='exams.blueprintversion')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blueprint_workflow_actions', to='accounts.accountprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_code', models.CharField(max_length=50, unique=True)),
                ('exam_type', models.CharField(choices=[('scholarship', 'Scholarship'), ('admission', 'Admission'), ('certification', 'Certification'), ('qualifying', 'Qualifying'), ('licensure', 'Licensure'), ('other', 'Other')], default='admission', max_length=20)),
                ('current_version_number', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_blueprints', to='exams.agency')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_blueprints', to='accounts.accountprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_blueprints', to='exams.blueprintcategory')),
                ('cloned_from_blueprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clones', to='exams.examblueprint')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_blueprints', to='accounts.accountprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='blueprintversion',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='exams.examblueprint'),
        ),
        migrations.CreateModel(
            name='BlueprintQuestionTypeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_item_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_type_requirements', to='exams.blueprintsection')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blueprint_requirements', to='exams.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='exams.subject')),
            ],
            options={
                'ordering': ['subject__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlueprintSectionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_item_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_requirements', to='exams.blueprintsection')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blueprint_section_requirements', to='exams.topic')),
            ],
        ),
        migrations.CreateModel(
            name='BlueprintDifficultyDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], max_length=20)),
                ('required_item_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_requirements', to='exams.blueprintsection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('blueprint_section', 'difficulty'), name='unique_blueprint_section_difficulty')],
            },
        ),
        migrations.AddConstraint(
            model_name='blueprintversion',
            constraint=models.UniqueConstraint(fields=('blueprint', 'version_number'), name='unique_blueprint_version_number'),
        ),
        migrations.AddConstraint(
            model_name='blueprintquestiontypedistribution',
            constraint=models.UniqueConstraint(fields=('blueprint_section', 'question_type'), name='unique_blueprint_section_question_type'),
        ),
        migrations.AddConstraint(
            model_name='blueprintsection',
            constraint=models.UniqueConstraint(fields=('blueprint_version', 'section_number'), name='unique_blueprint_section_number'),
        ),
        migrations.AddConstraint(
            model_name='blueprintsection',
            constraint=models.UniqueConstraint(fields=('blueprint_version', 'display_order'), name='unique_blueprint_section_display_order'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('subject', 'name'), name='unique_topic_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='blueprintsectiontopic',
            constraint=models.UniqueConstraint(fields=('blueprint_section', 'topic'), name='unique_blueprint_section_topic'),
        ),
    ]
