# Generated by Django 5.2.3 on 2026-08-03 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accountprofile_role'),
        ('exams', '0002_question_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('examination_period', models.CharField(blank=True, default='', max_length=150)),
                ('exam_type', models.CharField(blank=True, choices=[('scholarship', 'Scholarship'), ('admission', 'Admission'), ('certification', 'Certification'), ('qualifying', 'Qualifying'), ('licensure', 'Licensure'), ('other', 'Other')], default='admission', max_length=20)),
                ('instructions', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('academic_review', 'Academic review'), ('revision_required', 'Revision required'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sets', to='exams.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_exam_sets', to='accounts.accountprofile')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_exam_sets', to='accounts.accountprofile')),
                ('blueprint_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sets', to='exams.blueprintversion')),
                ('cloned_from_exam_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clones', to='exams.examset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exam_sets', to='accounts.accountprofile')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_exam_sets', to='accounts.accountprofile')),
            ],
            options={
                'db_table': 'exam_sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSetAssemblyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_version', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('selected_item_count', models.PositiveIntegerField(default=0)),
                ('rejected_item_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_runs', to='exams.examset')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_set_assembly_runs', to='accounts.accountprofile')),
            ],
            options={
                'db_table': 'exam_set_assembly_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSetQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField()),
                ('points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('selection_method', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_set_items', to='exams.blueprintsection')),
                ('exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exams.examset')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_set_items', to='exams.question')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_exam_set_questions', to='accounts.accountprofile')),
            ],
            options={
                'db_table': 'exam_set_questions',
                'ordering': ['display_order', 'selected_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSetQuestionReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='exams.examset')),
                ('exam_set_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='exams.examsetquestion')),
                ('new_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_questions', to='exams.question')),
                ('old_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replaced_in_exam_sets', to='exams.question')),
                ('replaced_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_set_replacements', to='accounts.accountprofile')),
            ],
            options={
                'db_table': 'exam_set_question_replacements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSetValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_code', models.CharField(max_length=50)),
                ('validation_name', models.CharField(max_length=150)),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('warning', 'Warning'), ('failed', 'Failed')], max_length=20)),
                ('expected_value', models.CharField(blank=True, default='', max_length=255)),
                ('actual_value', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='exams.examset')),
            ],
            options={
                'db_table': 'exam_set_validation_results',
                'ordering': ['-validated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSetWorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('academic_review', 'Academic review'), ('revision_required', 'Revision required'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], max_length=32, null=True)),
                ('new_status', models.CharField(choices=[('draft', 'Draft'), ('academic_review', 'Academic review'), ('revision_required', 'Revision required'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], max_length=32)),
                ('action', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='exams.examset')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_set_workflow_actions', to='accounts.accountprofile')),
            ],
            options={
                'db_table': 'exam_set_workflow_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSetAssemblyRunItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_selected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assembly_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exams.examsetassemblyrun')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_run_items', to='exams.question')),
            ],
            options={
                'db_table': 'exam_set_assembly_run_items',
                'constraints': [models.UniqueConstraint(fields=('assembly_run', 'question'), name='unique_exam_set_assembly_run_item')],
            },
        ),
        migrations.AddConstraint(
            model_name='examsetquestion',
            constraint=models.UniqueConstraint(fields=('exam_set', 'question'), name='unique_exam_set_question'),
        ),
        migrations.AddConstraint(
            model_name='examsetquestion',
            constraint=models.UniqueConstraint(fields=('exam_set', 'display_order'), name='unique_exam_set_question_display_order'),
        ),
    ]
