# Generated by Django 5.2.3 on 2026-08-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examset_examsetassemblyrun_examsetquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('academic_review', 'Academic review'), ('revision_required', 'Revision required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('retired', 'Retired'), ('archived', 'Archived')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='blueprintworkflowhistory',
            name='new_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('academic_review', 'Academic review'), ('revision_required', 'Revision required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('retired', 'Retired'), ('archived', 'Archived')], max_length=32),
        ),
        migrations.AlterField(
            model_name='blueprintworkflowhistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('academic_review', 'Academic review'), ('revision_required', 'Revision required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('retired', 'Retired'), ('archived', 'Archived')], max_length=32, null=True),
        ),
    ]
