# Generated by Django 5.2.3 on 2026-08-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examset_examsetassemblyrun_examsetquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examset',
            name='published_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
