# Generated by Django 5.2.3 on 2026-07-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordrecoverytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('ADMISSIONS_REVIEWER', 'ADMISSIONS_REVIEWER'), ('ITEM_WRITER', 'ITEM_WRITER'), ('ACADEMIC_REVIEWER', 'ACADEMIC_REVIEWER'), ('PROCTOR', 'PROCTOR'), ('PROCTOR_ADMIN', 'PROCTOR_ADMIN'), ('UNIVERSITY_ADMIN', 'UNIVERSITY_ADMIN'), ('TESTING_CENTER_ADMIN', 'TESTING_CENTER_ADMIN'), ('EXAM_ADMINISTRATOR', 'EXAM_ADMINISTRATOR'), ('SYSTEM_ADMIN', 'SYSTEM_ADMIN'), ('CHED_ADMIN', 'CHED_ADMIN'), ('DEPED_ADMIN', 'DEPED_ADMIN'), ('TESDA_ADMIN', 'TESDA_ADMIN'), ('EXECUTIVE', 'EXECUTIVE')], max_length=32),
        ),
    ]
