# Generated by Django 5.2.3 on 2026-07-14 01:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FOR_CORRECTION', 'For correction'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('lrn', models.CharField(blank=True, default='', max_length=12, verbose_name='LRN')),
                ('exam_cycle_id', models.CharField(blank=True, default='', max_length=64)),
                ('personal', models.JSONField(blank=True, default=dict)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('school', models.JSONField(blank=True, default=dict)),
                ('course_preferences', models.JSONField(blank=True, default=list)),
                ('review_step', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'REJECTED'), _negated=True), fields=('lrn', 'exam_cycle_id'), name='unique_active_lrn_per_exam_cycle'),
        ),
        migrations.AddConstraint(
            model_name='studentapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False), models.Q(('status', 'REJECTED'), _negated=True)), fields=('owner', 'exam_cycle_id'), name='unique_active_owner_per_exam_cycle'),
        ),
    ]
