# Generated by Django 5.2.3 on 2026-07-14 08:06

import apps.applications.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_student_application_password_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Step2Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('lrn', models.CharField(max_length=12)),
                ('lrn_profile', models.JSONField(default=dict)),
                ('configuration_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('PASSED', 'Passed'), ('MANUAL_REVIEW', 'Manual review'), ('REJECTED', 'Rejected')], default='IN_PROGRESS', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step2_verification', to='applications.studentapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Step2VerificationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_student_id_verification', models.BooleanField(default=False)),
                ('require_student_id_front', models.BooleanField(default=True)),
                ('require_student_id_back', models.BooleanField(default=True)),
                ('enable_student_id_information_extraction', models.BooleanField(default=False)),
                ('compare_student_name', models.BooleanField(default=False)),
                ('compare_school_name', models.BooleanField(default=False)),
                ('name_match_threshold', models.DecimalField(decimal_places=2, default=85, max_digits=5)),
                ('school_match_threshold', models.DecimalField(decimal_places=2, default=85, max_digits=5)),
                ('enable_facial_comparison', models.BooleanField(default=False)),
                ('facial_similarity_threshold', models.DecimalField(decimal_places=2, default=85, max_digits=5)),
                ('allow_manual_review', models.BooleanField(default=True)),
                ('maximum_verification_attempts', models.PositiveSmallIntegerField(default=5)),
                ('effective_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step2_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationIdentityMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('STUDENT_ID_FRONT', 'Student ID front'), ('STUDENT_ID_BACK', 'Student ID back'), ('SELFIE', 'Selfie')], max_length=24)),
                ('file', models.FileField(upload_to=apps.applications.models.identity_media_upload_to)),
                ('content_type', models.CharField(max_length=32)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='applications.step2verification')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('verification', 'media_type'), name='unique_step2_media_type')],
            },
        ),
    ]
