# Generated by Django 5.2.3 on 2026-07-22 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_allow_multiple_manual_lrn_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('event', models.CharField(max_length=120)),
                ('outcome', models.CharField(db_index=True, max_length=20)),
                ('registration_id', models.CharField(blank=True, default='', max_length=80)),
                ('applicant_id', models.CharField(blank=True, default='', max_length=80)),
                ('account_id', models.CharField(blank=True, default='', max_length=80)),
                ('actor_user_id', models.CharField(blank=True, default='', max_length=80)),
                ('actor_role', models.CharField(blank=True, default='', max_length=80)),
                ('session_id', models.CharField(blank=True, default='', max_length=120)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='applications.studentapplication')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'outcome', '-created_at'], name='application_action_0c655a_idx'), models.Index(fields=['registration_id'], name='application_registr_14584d_idx')],
            },
        ),
    ]
