# Generated by Django 5.2.3 on 2026-07-30

import django.db.models.deletion
from django.db import migrations, models


def copy_json_sections_to_holding_tables(apps, schema_editor):
    StudentApplication = apps.get_model("applications", "StudentApplication")
    StudentApplicationAddress = apps.get_model("applications", "StudentApplicationAddress")
    StudentApplicationCoursePreference = apps.get_model("applications", "StudentApplicationCoursePreference")
    StudentApplicationPersonalInfo = apps.get_model("applications", "StudentApplicationPersonalInfo")
    StudentApplicationReviewInfo = apps.get_model("applications", "StudentApplicationReviewInfo")
    StudentApplicationSchoolInfo = apps.get_model("applications", "StudentApplicationSchoolInfo")
    StudentApplicationAdditionalField = apps.get_model("applications", "StudentApplicationAdditionalField")

    known_section_keys = {
        "personal": {
            "firstName", "middleName", "lastName", "suffix", "extensionName", "dateOfBirth",
            "sex", "email", "mobile", "identityVerificationStatus",
        },
        "address": {"region", "province", "city", "barangay", "street", "postalCode"},
        "school": {
            "lrn", "schoolId", "name", "academicTrack", "gradeLevel",
            "enrollmentStatus", "schoolYear", "gwa",
        },
        "reviewStep": {
            "privacyConsent", "declarationAccepted", "requiresAdmissionsReviewerAttention",
            "attentionReason", "reviewerDecision", "reviewerReason", "requiredCorrections",
            "reviewedBy", "reviewedAt",
        },
    }

    def additional_rows(application, section, data):
        return [
            StudentApplicationAdditionalField(
                application=application,
                section=section,
                field_key=key,
                field_value=str(value),
            )
            for key, value in data.items()
            if key not in known_section_keys[section] and value not in (None, "")
        ]

    for application in StudentApplication.objects.all().iterator():
        personal = application.personal or {}
        address = application.address or {}
        school = application.school or {}
        review_step = application.review_step or {}
        course_preferences = application.course_preferences or []

        if personal:
            StudentApplicationPersonalInfo.objects.create(
                application=application,
                first_name=personal.get("firstName", ""),
                middle_name=personal.get("middleName", ""),
                last_name=personal.get("lastName", ""),
                suffix=personal.get("suffix") or personal.get("extensionName", ""),
                date_of_birth=personal.get("dateOfBirth", ""),
                sex=personal.get("sex", ""),
                email=personal.get("email", ""),
                mobile=personal.get("mobile", ""),
                identity_verification_status=personal.get("identityVerificationStatus", ""),
            )
            StudentApplicationAdditionalField.objects.bulk_create(additional_rows(application, "personal", personal))

        if address:
            StudentApplicationAddress.objects.create(
                application=application,
                region=address.get("region", ""),
                province=address.get("province", ""),
                city=address.get("city", ""),
                barangay=address.get("barangay", ""),
                street=address.get("street", ""),
                postal_code=address.get("postalCode", ""),
            )
            StudentApplicationAdditionalField.objects.bulk_create(additional_rows(application, "address", address))

        if school:
            StudentApplicationSchoolInfo.objects.create(
                application=application,
                lrn=school.get("lrn", ""),
                school_id=school.get("schoolId", ""),
                name=school.get("name", ""),
                academic_track=school.get("academicTrack", ""),
                grade_level=school.get("gradeLevel", ""),
                enrollment_status=school.get("enrollmentStatus", ""),
                school_year=school.get("schoolYear", ""),
                gwa=school.get("gwa", ""),
            )
            StudentApplicationAdditionalField.objects.bulk_create(additional_rows(application, "school", school))

        if review_step:
            corrections = review_step.get("requiredCorrections", [])
            StudentApplicationReviewInfo.objects.create(
                application=application,
                privacy_consent=review_step.get("privacyConsent") is True,
                declaration_accepted=review_step.get("declarationAccepted") is True,
                requires_admissions_reviewer_attention=review_step.get("requiresAdmissionsReviewerAttention") is True,
                attention_reason=review_step.get("attentionReason", ""),
                reviewer_decision=review_step.get("reviewerDecision", ""),
                reviewer_reason=review_step.get("reviewerReason", ""),
                required_corrections="\n".join(str(item) for item in corrections if str(item).strip()),
                reviewed_by=review_step.get("reviewedBy", ""),
                reviewed_at=review_step.get("reviewedAt", ""),
            )
            StudentApplicationAdditionalField.objects.bulk_create(
                additional_rows(application, "reviewStep", review_step)
            )

        rows = []
        for index, preference in enumerate(course_preferences):
            if not isinstance(preference, dict):
                continue
            rows.append(
                StudentApplicationCoursePreference(
                    application=application,
                    university=preference.get("university", ""),
                    course=preference.get("course", ""),
                    display_order=index,
                )
            )
        if rows:
            StudentApplicationCoursePreference.objects.bulk_create(rows)


def copy_holding_tables_to_json_sections(apps, schema_editor):
    StudentApplication = apps.get_model("applications", "StudentApplication")

    def related_or_none(application, attribute_name):
        try:
            return getattr(application, attribute_name)
        except AttributeError:
            return None

    for application in StudentApplication.objects.all().iterator():
        personal = related_or_none(application, "personal_info")
        address = related_or_none(application, "address_info")
        school = related_or_none(application, "school_info")
        review_step = related_or_none(application, "review_info")

        application.personal = {} if personal is None else {
            "firstName": personal.first_name,
            "middleName": personal.middle_name,
            "lastName": personal.last_name,
            "suffix": personal.suffix,
            "dateOfBirth": personal.date_of_birth,
            "sex": personal.sex,
            "email": personal.email,
            "mobile": personal.mobile,
            "identityVerificationStatus": personal.identity_verification_status,
        }
        application.personal.update(
            {
                field.field_key: field.field_value
                for field in application.additional_fields.filter(section="personal")
            }
        )
        application.address = {} if address is None else {
            "region": address.region,
            "province": address.province,
            "city": address.city,
            "barangay": address.barangay,
            "street": address.street,
            "postalCode": address.postal_code,
        }
        application.address.update(
            {
                field.field_key: field.field_value
                for field in application.additional_fields.filter(section="address")
            }
        )
        application.school = {} if school is None else {
            "lrn": school.lrn,
            "schoolId": school.school_id,
            "name": school.name,
            "academicTrack": school.academic_track,
            "gradeLevel": school.grade_level,
            "enrollmentStatus": school.enrollment_status,
            "schoolYear": school.school_year,
            "gwa": school.gwa,
        }
        application.school.update(
            {
                field.field_key: field.field_value
                for field in application.additional_fields.filter(section="school")
            }
        )
        application.course_preferences = [
            {"university": preference.university, "course": preference.course}
            for preference in application.course_preference_rows.order_by("display_order", "id")
        ]
        application.review_step = {} if review_step is None else {
            "privacyConsent": review_step.privacy_consent,
            "declarationAccepted": review_step.declaration_accepted,
            "requiresAdmissionsReviewerAttention": review_step.requires_admissions_reviewer_attention,
            "attentionReason": review_step.attention_reason,
            "reviewerDecision": review_step.reviewer_decision,
            "reviewerReason": review_step.reviewer_reason,
            "requiredCorrections": [item for item in review_step.required_corrections.splitlines() if item],
            "reviewedBy": review_step.reviewed_by,
            "reviewedAt": review_step.reviewed_at,
        }
        application.review_step.update(
            {
                field.field_key: field.field_value
                for field in application.additional_fields.filter(section="reviewStep")
            }
        )
        application.save(update_fields=["personal", "address", "school", "course_preferences", "review_step"])


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_studentapplication_candidate_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentApplicationAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("region", models.CharField(blank=True, default="", max_length=120)),
                ("province", models.CharField(blank=True, default="", max_length=120)),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("barangay", models.CharField(blank=True, default="", max_length=120)),
                ("street", models.CharField(blank=True, default="", max_length=255)),
                ("postal_code", models.CharField(blank=True, default="", max_length=20)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_info",
                        to="applications.studentapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentApplicationCoursePreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("university", models.CharField(blank=True, default="", max_length=255)),
                ("course", models.CharField(blank=True, default="", max_length=255)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_preference_rows",
                        to="applications.studentapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StudentApplicationPersonalInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(blank=True, default="", max_length=150)),
                ("middle_name", models.CharField(blank=True, default="", max_length=150)),
                ("last_name", models.CharField(blank=True, default="", max_length=150)),
                ("suffix", models.CharField(blank=True, default="", max_length=50)),
                ("date_of_birth", models.CharField(blank=True, default="", max_length=20)),
                ("sex", models.CharField(blank=True, default="", max_length=30)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("mobile", models.CharField(blank=True, default="", max_length=30)),
                ("identity_verification_status", models.CharField(blank=True, default="", max_length=40)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_info",
                        to="applications.studentapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentApplicationReviewInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("privacy_consent", models.BooleanField(default=False)),
                ("declaration_accepted", models.BooleanField(default=False)),
                ("requires_admissions_reviewer_attention", models.BooleanField(default=False)),
                ("attention_reason", models.TextField(blank=True, default="")),
                ("reviewer_decision", models.CharField(blank=True, default="", max_length=40)),
                ("reviewer_reason", models.TextField(blank=True, default="")),
                ("required_corrections", models.TextField(blank=True, default="")),
                ("reviewed_by", models.CharField(blank=True, default="", max_length=80)),
                ("reviewed_at", models.CharField(blank=True, default="", max_length=40)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_info",
                        to="applications.studentapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentApplicationSchoolInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lrn", models.CharField(blank=True, default="", max_length=12)),
                ("school_id", models.CharField(blank=True, default="", max_length=64)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("academic_track", models.CharField(blank=True, default="", max_length=120)),
                ("grade_level", models.CharField(blank=True, default="", max_length=40)),
                ("enrollment_status", models.CharField(blank=True, default="", max_length=80)),
                ("school_year", models.CharField(blank=True, default="", max_length=20)),
                ("gwa", models.CharField(blank=True, default="", max_length=20)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_info",
                        to="applications.studentapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentApplicationAdditionalField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("section", models.CharField(max_length=40)),
                ("field_key", models.CharField(max_length=120)),
                ("field_value", models.TextField(blank=True, default="")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_fields",
                        to="applications.studentapplication",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "section", "field_key"),
                        name="unique_application_additional_field",
                    ),
                ],
            },
        ),
        migrations.RunPython(copy_json_sections_to_holding_tables, copy_holding_tables_to_json_sections),
        migrations.RemoveField(
            model_name="studentapplication",
            name="address",
        ),
        migrations.RemoveField(
            model_name="studentapplication",
            name="course_preferences",
        ),
        migrations.RemoveField(
            model_name="studentapplication",
            name="personal",
        ),
        migrations.RemoveField(
            model_name="studentapplication",
            name="review_step",
        ),
        migrations.RemoveField(
            model_name="studentapplication",
            name="school",
        ),
    ]
