# Generated by Django 5.2.3 on 2026-07-30 07:29

import apps.applications.models
import base64
import binascii
import django.db.models.deletion
import hashlib
import uuid
from django.core.files.base import ContentFile
from django.db import migrations, models


def _selfie_content_file(data_url):
    prefix, separator, encoded = str(data_url or "").partition(",")
    if separator != "," or ";base64" not in prefix:
        return None, "", 0, ""
    content_type = prefix.removeprefix("data:").split(";", 1)[0]
    if content_type not in {"image/jpeg", "image/png"}:
        return None, "", 0, ""
    try:
        image_bytes = base64.b64decode(encoded, validate=True)
    except (binascii.Error, ValueError):
        return None, "", 0, ""
    if content_type == "image/png" and not image_bytes.startswith(b"\x89PNG\r\n\x1a\n"):
        return None, "", 0, ""
    if content_type == "image/jpeg" and not image_bytes.startswith(b"\xff\xd8\xff"):
        return None, "", 0, ""

    extension = "png" if content_type == "image/png" else "jpg"
    return (
        ContentFile(image_bytes, name=f"registration-selfie.{extension}"),
        content_type,
        len(image_bytes),
        hashlib.sha256(image_bytes).hexdigest(),
    )


def move_selfies_to_registration_table(apps, schema_editor):
    ApplicationIdentityMedia = apps.get_model("applications", "ApplicationIdentityMedia")
    StudentApplicationAdditionalField = apps.get_model("applications", "StudentApplicationAdditionalField")
    Step2Verification = apps.get_model("applications", "Step2Verification")
    RegistrationSelfieMedia = apps.get_model("applications", "RegistrationSelfieMedia")

    selfie_rows = ApplicationIdentityMedia.objects.filter(media_type="SELFIE").order_by("created_at", "id")
    for media in selfie_rows.iterator():
        RegistrationSelfieMedia.objects.update_or_create(
            verification_id=media.verification_id,
            defaults={
                "file": media.file,
                "content_type": media.content_type,
                "size": media.size,
                "sha256": media.sha256,
                "created_at": media.created_at,
            },
        )
    selfie_rows.delete()

    additional_selfie_rows = StudentApplicationAdditionalField.objects.filter(
        section="personal",
        field_key="selfiePhotoUrl",
    )
    for field in additional_selfie_rows.iterator():
        verification = Step2Verification.objects.filter(application_id=field.application_id).first()
        if verification is None:
            continue
        file, content_type, size, sha256 = _selfie_content_file(field.field_value)
        if file is None:
            continue
        RegistrationSelfieMedia.objects.update_or_create(
            verification_id=verification.id,
            defaults={
                "file": file,
                "content_type": content_type,
                "size": size,
                "sha256": sha256,
            },
        )
    additional_selfie_rows.delete()


def move_selfies_to_identity_media_table(apps, schema_editor):
    ApplicationIdentityMedia = apps.get_model("applications", "ApplicationIdentityMedia")
    RegistrationSelfieMedia = apps.get_model("applications", "RegistrationSelfieMedia")

    for selfie in RegistrationSelfieMedia.objects.order_by("created_at", "id").iterator():
        ApplicationIdentityMedia.objects.update_or_create(
            verification_id=selfie.verification_id,
            media_type="SELFIE",
            defaults={
                "file": selfie.file,
                "content_type": selfie.content_type,
                "size": selfie.size,
                "sha256": selfie.sha256,
                "created_at": selfie.created_at,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_student_application_holding_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSelfieMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.applications.models.registration_selfie_upload_to)),
                ('content_type', models.CharField(max_length=32)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'verification',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='registration_selfie',
                        to='applications.step2verification',
                    ),
                ),
            ],
        ),
        migrations.RunPython(move_selfies_to_registration_table, move_selfies_to_identity_media_table),
    ]
