# Generated by Django 5.2.3 on 2026-07-30 07:50

import django.db.models.deletion
from django.db import migrations, models


def backfill_selfie_applications(apps, schema_editor):
    RegistrationSelfieMedia = apps.get_model("applications", "RegistrationSelfieMedia")
    for selfie in RegistrationSelfieMedia.objects.select_related("verification").iterator():
        if selfie.application_id is None and selfie.verification_id and selfie.verification.application_id:
            selfie.application_id = selfie.verification.application_id
            selfie.save(update_fields=["application"])


def clear_backfilled_selfie_applications(apps, schema_editor):
    RegistrationSelfieMedia = apps.get_model("applications", "RegistrationSelfieMedia")
    RegistrationSelfieMedia.objects.filter(verification__isnull=False).update(application=None)


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_registrationselfiemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationselfiemedia',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_selfie', to='applications.studentapplication'),
        ),
        migrations.AlterField(
            model_name='registrationselfiemedia',
            name='verification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_selfie', to='applications.step2verification'),
        ),
        migrations.RunPython(backfill_selfie_applications, clear_backfilled_selfie_applications),
        migrations.AddConstraint(
            model_name='registrationselfiemedia',
            constraint=models.CheckConstraint(condition=models.Q(('verification__isnull', False), ('application__isnull', False), _connector='OR'), name='registration_selfie_has_owner'),
        ),
    ]
