# Generated by Django 5.2.3 on 2026-08-03

import apps.applications.models
import django.db.models.deletion
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_registrationselfiemedia_application_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentApplicationAdditionalAttachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("registration_session_id", models.CharField(blank=True, default="", max_length=120)),
                ("section", models.CharField(max_length=40)),
                ("field_key", models.CharField(max_length=120)),
                ("file", models.FileField(upload_to=apps.applications.models.registration_attachment_upload_to)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=32)),
                ("size", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_attachments",
                        to="applications.studentapplication",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="studentapplicationadditionalattachment",
            constraint=models.CheckConstraint(
                condition=models.Q(application__isnull=False) | ~models.Q(registration_session_id=""),
                name="additional_attachment_has_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentapplicationadditionalattachment",
            constraint=models.UniqueConstraint(
                condition=models.Q(application__isnull=False),
                fields=("application", "section", "field_key"),
                name="unique_application_additional_attachment",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentapplicationadditionalattachment",
            constraint=models.UniqueConstraint(
                condition=~models.Q(registration_session_id=""),
                fields=("registration_session_id", "section", "field_key"),
                name="unique_session_additional_attachment",
            ),
        ),
    ]
