# Generated by Django 5.2.3 on 2026-08-06 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_studentapplicationadditionalattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='bulk_upload_row_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='completion_status',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('PENDING_STUDENT_COMPLETION', 'Pending student completion')], default='COMPLETE', max_length=40),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='submission_source',
            field=models.CharField(choices=[('STUDENT_REGISTRATION', 'Student registration'), ('ADMISSIONS_BULK_UPLOAD', 'Admissions bulk upload')], default='STUDENT_REGISTRATION', max_length=40),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='submitted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_bulk_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ApplicationBulkUploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_version', models.CharField(max_length=40)),
                ('exam_cycle_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('VALIDATED', 'Validated'), ('CONFIRMING', 'Confirming'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed with errors'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='UPLOADED', max_length=40)),
                ('performed_by_role_snapshot', models.CharField(max_length=80)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary_counts', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_bulk_upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='bulk_upload_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imported_applications', to='applications.applicationbulkuploadbatch'),
        ),
        migrations.CreateModel(
            name='ApplicationBulkUploadRowResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('FIELD_ERROR', 'Field error'), ('CONFLICT', 'Conflict'), ('IMPORTED', 'Imported'), ('IMPORT_FAILED', 'Import failed')], max_length=40)),
                ('submitted_lrn', models.CharField(blank=True, default='', max_length=12)),
                ('submitted_email', models.EmailField(blank=True, default='', max_length=254)),
                ('row_snapshot', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_upload_row_results', to='applications.studentapplication')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_results', to='applications.applicationbulkuploadbatch')),
            ],
            options={
                'ordering': ['row_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_bulk_upload_row_number_per_batch')],
            },
        ),
    ]
