# Generated by Django 5.2.3 on 2026-08-06 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_bulk_upload_application_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_cycle_id', models.CharField(blank=True, default='', max_length=64)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('test_center', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('total_slots', models.PositiveIntegerField()),
                ('remaining_slots', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='exam_status',
            field=models.CharField(blank=True, choices=[('SCHEDULED', 'Scheduled')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='assigned_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_applications', to='applications.examslot'),
        ),
    ]
