# Generated by Django 5.2.3 on 2026-08-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_drop_legacy_studentapplication_source'),
        ('applications', '0015_examslot_studentapplication_exam_status_and_more'),
    ]

    operations = [
    ]
