from django.urls import path

from .views import (
    ApplicationCreateView,
    ApplicationAdditionalAttachmentView,
    ApplicationDetailView,
    ApplicationIdentityMediaView,
    ApplicationReviewerDecisionView,
    ApplicationReviewQueueView,
    ApplicationSubmittedAuditLogView,
    ApplicationSubmitView,
    BulkUploadBatchDetailView,
    BulkUploadConfirmView,
    BulkUploadErrorsCsvView,
    BulkUploadTemplateView,
    BulkUploadValidateView,
    ExamSlotListView,
    LrnVerificationView,
    MyApplicationExamSlotView,
    MyApplicationView,
    PublicStep2ConfigurationView,
    RegistrationEmailOtpRequestView,
    RegistrationEmailOtpVerifyView,
    RegistrationAttachmentUploadView,
    RegistrationIdentitySelfieFaceValidationView,
    RegistrationManualIdentitySelfieFaceValidationView,
    RegistrationIdentitySelfieView,
    Step2ConfigurationAdminView,
    Step2VerificationView,
    Step2ManualDecisionView,
)

urlpatterns = [
    path("me/", MyApplicationView.as_view(), name="mine"),
    path("me/exam-slot/", MyApplicationExamSlotView.as_view(), name="mine-exam-slot"),
    path("exam-slots/", ExamSlotListView.as_view(), name="exam-slots"),
    path("registration/lrn/verify/", LrnVerificationView.as_view(), name="verify-lrn"),
    path("registration/email-otp/request/", RegistrationEmailOtpRequestView.as_view(), name="registration-email-otp-request"),
    path("registration/email-otp/verify/", RegistrationEmailOtpVerifyView.as_view(), name="registration-email-otp-verify"),
    path("registration/attachments/", RegistrationAttachmentUploadView.as_view(), name="registration-attachment-upload"),
    path("registration/identity/selfie/", RegistrationIdentitySelfieView.as_view(), name="registration-identity-selfie"),
    path("registration/identity/selfie-face/", RegistrationIdentitySelfieFaceValidationView.as_view(), name="registration-identity-selfie-face"),
    path("registration/identity/manual-selfie-face/", RegistrationManualIdentitySelfieFaceValidationView.as_view(), name="registration-manual-identity-selfie-face"),
    path("registration/step-2/configuration/", PublicStep2ConfigurationView.as_view(), name="step2-public-configuration"),
    path("registration/step-2/", Step2VerificationView.as_view(), name="step2-verification"),
    path("configuration/step-2/", Step2ConfigurationAdminView.as_view(), name="step2-configuration-admin"),
    path("registration/step-2/<uuid:verification_id>/manual-decision/", Step2ManualDecisionView.as_view(), name="step2-manual-decision"),
    path("audit/registration-submitted/", ApplicationSubmittedAuditLogView.as_view(), name="registration-submitted-audit"),
    path("review-queue/", ApplicationReviewQueueView.as_view(), name="review-queue"),
    path("bulk-upload/template/", BulkUploadTemplateView.as_view(), name="bulk-upload-template"),
    path("bulk-upload/validate/", BulkUploadValidateView.as_view(), name="bulk-upload-validate"),
    path("bulk-upload/<uuid:batch_id>/", BulkUploadBatchDetailView.as_view(), name="bulk-upload-detail"),
    path("bulk-upload/<uuid:batch_id>/errors.csv", BulkUploadErrorsCsvView.as_view(), name="bulk-upload-errors"),
    path("bulk-upload/<uuid:batch_id>/confirm/", BulkUploadConfirmView.as_view(), name="bulk-upload-confirm"),
    path("", ApplicationCreateView.as_view(), name="create"),
    path("<uuid:application_id>/review-decision/", ApplicationReviewerDecisionView.as_view(), name="review-decision"),
    path("<uuid:application_id>/identity-media/<str:media_type>/", ApplicationIdentityMediaView.as_view(), name="identity-media"),
    path("<uuid:application_id>/attachments/<uuid:attachment_id>/", ApplicationAdditionalAttachmentView.as_view(), name="additional-attachment"),
    path("<uuid:application_id>/", ApplicationDetailView.as_view(), name="detail"),
    path("<uuid:application_id>/submit/", ApplicationSubmitView.as_view(), name="submit"),
]
