# Generated by Django 5.2.3 on 2026-08-03 09:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_seed_pwd_registration_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('classification', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=20)),
                ('region', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('president_rector', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('established_year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_universities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=255)),
                ('program_code', models.CharField(max_length=40)),
                ('program_name', models.CharField(max_length=255)),
                ('degree_type', models.CharField(choices=[('Bachelor of Science', 'Bachelor of Science'), ('Bachelor of Arts', 'Bachelor of Arts'), ('Bachelor of Fine Arts', 'Bachelor of Fine Arts'), ('Associate', 'Associate')], max_length=40)),
                ('major_specialization', models.CharField(blank=True, default='', max_length=255)),
                ('duration_years', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('total_units', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('cutoff_percentile', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_college_courses', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_courses', to='configuration.university')),
            ],
            options={
                'ordering': ['college_name', 'program_code', 'program_name'],
            },
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['classification', 'status'], name='configurati_classif_4e0563_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['region', 'city'], name='configurati_region_873008_idx'),
        ),
        migrations.AddIndex(
            model_name='collegecourse',
            index=models.Index(fields=['university', 'status'], name='configurati_univers_a36d13_idx'),
        ),
        migrations.AddIndex(
            model_name='collegecourse',
            index=models.Index(fields=['university', 'college_name'], name='configurati_univers_452959_idx'),
        ),
        migrations.AddConstraint(
            model_name='collegecourse',
            constraint=models.UniqueConstraint(fields=('university', 'program_code'), name='unique_university_program_code'),
        ),
    ]
