# Generated by Django 5.2.3 on 2026-08-07 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_configurablefield_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id_snapshot', models.PositiveIntegerField(db_index=True)),
                ('action', models.CharField(db_index=True, max_length=20)),
                ('actor_user_id', models.CharField(blank=True, default='', max_length=80)),
                ('before_json', models.JSONField(blank=True, default=dict)),
                ('after_json', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='configuration.configurablefield')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['field_id_snapshot', '-created_at'], name='configurati_field_i_3cea8b_idx')],
            },
        ),
    ]
