from .local import *  # noqa: F403

AUTH_LOCAL_EXPOSE_OTP = True

_REHEARSAL_ORIGIN = "http://127.0.0.1:3002"
CSRF_TRUSTED_ORIGINS = [*CSRF_TRUSTED_ORIGINS, _REHEARSAL_ORIGIN]  # noqa: F405
CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS
